#!/bin/bash

EXECUTABLE="./mingle_master_production"

# ── Energy sweep: 100 points log-spaced ─────────────

mapfile -t ENERGIES < <(awk 'BEGIN {
    n_total = 101

    n1 = 70   # points in 1–100 MeV (dense region)
    n2 = n_total - n1  # remaining points

    # --- Segment 1: 0.01 → 100 MeV ---
    lo1 = log(0.01)
    hi1 = log(100)

    for (i = 0; i < n1; i++) {
        e = exp(lo1 + i * (hi1 - lo1) / (n1 - 1))
        printf "%.4f\n", e
    }

    # --- Segment 2: 100 → 1000MeV ---
    lo2 = log(100)
    hi2 = log(1000)

    # start from i=1 to avoid duplicating 100 MeV
    for (i = 1; i < n2; i++) {
        e = exp(lo2 + i * (hi2 - lo2) / (n2 - 1))
        printf "%.4f\n", e
    }
}')

# ── Fixed surface settings (mid-range) ────────────────────────────────────────
WRAPPING_REFLECTIVITY="0.98"
WRAPPING_FINISH="groundbackpainted"
WRAPPING_SIGMA="0.2"
WRAPPING_LOBE="1.0"

# ── Fixed beam settings ────────────────────────────────────────────────────────
PARTICLE="e+"
N_EVENTS=1000
ENABLE_PATH_TRACKING="0"

OUTPUT_DIR="energy_sweep_${PARTICLE}_1MeV_to_100GeV_nevents${N_EVENTS}"
mkdir -p "$OUTPUT_DIR"

# ── Backup run.mac ─────────────────────────────────────────────────────────────
if [ ! -f "run.mac.bak" ]; then
    cp run.mac run.mac.bak
    echo ">>> Backed up run.mac to run.mac.bak"
fi

TOTAL=${#ENERGIES[@]}
echo ">>> Energy range: ${ENERGIES[0]} MeV  →  ${ENERGIES[$((TOTAL-1))]} MeV"
echo ">>> Steps:        $TOTAL"
echo ">>> Events/run:   $N_EVENTS"
echo ">>> Output dir:   $OUTPUT_DIR"
echo ""

RUN=0
DONE=0
SKIPPED=0

for ENERGY_MEV in "${ENERGIES[@]}"; do

    RUN=$(( RUN + 1 ))

    # Encode energy in filename (replace . with p to avoid filesystem issues)
    ENERGY_TAG=$(echo "$ENERGY_MEV" | tr '.' 'p')
    OUTFILE="${OUTPUT_DIR}/scoring_e${ENERGY_TAG}MeV.root"

    if [ -f "$OUTFILE" ]; then
        echo "[${RUN}/${TOTAL}] SKIP (exists): $OUTFILE"
        SKIPPED=$(( SKIPPED + 1 ))
        continue
    fi

    echo "[${RUN}/${TOTAL}] energy=${ENERGY_MEV} MeV"

    cat > run.mac << EOF
# run.mac — auto-generated by run_energy_sweep.sh
/run/setCut 0.001 mm
/cuts/setLowEdge 100 eV

/run/initialize

# --- PRIMARY BEAM SETTINGS ---
/gps/particle ${PARTICLE}
/gps/energy ${ENERGY_MEV} MeV

/gps/pos/type Plane
/gps/pos/shape Rectangle
/gps/pos/centre 11 0 0 mm
/gps/pos/rot1 0 1 0
/gps/pos/rot2 0 0 1
/gps/pos/halfx 314 mm
/gps/pos/halfy 500 mm
/gps/direction -1 0 0

/run/beamOn ${N_EVENTS}
EOF
    ENABLE_PATH_TRACKING=0 \
    ENABLE_PARENTAGE=0 \
    WRAPPING_REFLECTIVITY=$WRAPPING_REFLECTIVITY \
    WRAPPING_FINISH=$WRAPPING_FINISH \
    WRAPPING_SIGMA=$WRAPPING_SIGMA \
    WRAPPING_LOBE=$WRAPPING_LOBE \
    ENABLE_PATH_TRACKING=$ENABLE_PATH_TRACKING \
        $EXECUTABLE run.mac > /dev/null 2>&1

    if [ -f "scoring.root" ]; then
        mv scoring.root "$OUTFILE"
        echo "    -> Saved: $OUTFILE"
        DONE=$(( DONE + 1 ))
    else
        echo "    -> WARNING: no output produced"
    fi

done

# ── Restore run.mac ────────────────────────────────────────────────────────────
cp run.mac.bak run.mac
echo ""
echo ">>> Restored original run.mac"
echo ">>> Done. Completed: $DONE  Skipped: $SKIPPED  Total: $TOTAL"